/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dialog;
import static java.lang.Boolean.FALSE;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Livros;
import model.bean.Usuarios;
import model.dao.LivroDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author Lenovo
 */
public class TelaCarrinho extends javax.swing.JFrame {

    /**
     * Creates new form TelaCarrinho
     */
    
    public List<Livros> cesta = new ArrayList<Livros>();

    public List<Livros> getCesta() {
        return cesta;
    }

    public void setCesta(List<Livros> cesta) {
        this.cesta = cesta;
    }
    
    public TelaCarrinho(List<Livros> carrinho) {
        initComponents();
    
        //Ordenação da tabela
        DefaultTableModel modelo = (DefaultTableModel) jtLivros.getModel();
        jtLivros.setRowSorter(new TableRowSorter(modelo));
        
        txtQuantidade.setText(String.format("%d", carrinho.size()));
        // pega a cesta que veio da tela buscar
        cesta = carrinho;
        //Chamando a readJtable para assim que abrir a pagina ja fazer a leitura dos dados
        readJtable();

        
    }
    public void readJtable() {
        //metodo para fazer a leitura da tabela
 
        
        DefaultTableModel modelo = (DefaultTableModel) jtLivros.getModel();
        modelo.setNumRows(0);
        LivroDAO livroDAO = new LivroDAO();

        if(!cesta.isEmpty()){
            for (Livros livro : cesta) {
                modelo.addRow(new Object[]{
                livro.getId(), livro.getNome(),
                livro.getAutor(), livro.getAssunto(),
                livro.getStatus()
                });

            }
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtLivros = new javax.swing.JTable();
        jButtonFinalizaPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();

        setTitle("Carrinho");
        setLocation(new java.awt.Point(350, 50));

        jtLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Assunto", "Autor", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtLivros);

        jButtonFinalizaPedido.setBackground(new java.awt.Color(255, 55, 55));
        jButtonFinalizaPedido.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFinalizaPedido.setText("Finalizar pedido");
        jButtonFinalizaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizaPedidoActionPerformed(evt);
            }
        });

        jLabel1.setText("LIVROS QUE ESTÃO NO CARRINHO");

        jLabel2.setText("Quantidade:");

        txtQuantidade.setEditable(false);
        txtQuantidade.setText("0");
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizaPedido)
                        .addGap(11, 11, 11)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFinalizaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizaPedidoActionPerformed
        // TODO add your handling code here:
        if(cesta.size() == 0){
            JOptionPane.showMessageDialog(null, "Você deve adicionar um livro no carrinho primeiro");
            //new TelaBuscar("").setVisible(true);
            this.dispose();
        }
        else{
            Usuarios user = new Usuarios();
            UsuarioDAO dao = new UsuarioDAO();
            
            // Vou em uma gambiarra com caixas de dialogo
            
            String email;
            
            email = JOptionPane.showInputDialog("Digite seu email:");
            
            user = dao.buscaUsuarioPorEmail(email);
            
            while(user.getEmail() == "null"){
                email = JOptionPane.showInputDialog(null, "Digite se email:", "EMAIL INCORRETO!", HEIGHT);
            
                user = dao.buscaUsuarioPorEmail(email);
            }
            
            
            // coloca o cpf do usuario que vai fazer o emprestimo e muda o status
            for(Livros livro : cesta){
                livro.setCpfUserEmp(user.getCpf());
                livro.setStatus(FALSE);
            }
            
            // faz o emprestimo
            LivroDAO dao1 = new LivroDAO();
            dao1.fazEmprestimo(cesta);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonFinalizaPedidoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private List<Livros> carrinho;
            public void run() {
                new TelaCarrinho(carrinho).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizaPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtLivros;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
